<?xml version="1.0"?>
<robot name="base_cabinet" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="drawer" params="prefix name parent xyz">
    <xacro:box_link prefix="${prefix}" link_name="${name}_front_panel" mass="${drawer_front_panel_mass}"
                    xdim="${drawer_front_panel_xdim}" ydim="${drawer_front_panel_ydim}"
                    zdim="${drawer_front_panel_zdim}"
                    material="Oak"/>

    <joint name="${prefix}_${name}_front_panel_joint" type="prismatic">
      <parent link="${parent}"/>
      <child link="${prefix}_${name}_front_panel"/>
      <limit effort="10" lower="0" upper="${c3_drawer_interior_xdim}" velocity="1"/>
      <dynamics damping="100" friction="0.1"/>
      <origin xyz="${xyz}"/>
      <axis xyz="1 0 0"/>
    </joint>

    <xacro:handle prefix="${prefix}" name="${name}" parent="${prefix}_${name}_front_panel"
                  xyz="${drawer_front_panel_xdim/2} 0 ${drawer_front_panel_zdim/2-0.05}"/>

    <xacro:drawer_interior prefix="${prefix}" name="${name}_interior" parent="${prefix}_${name}_front_panel"
                           xyz="${(-drawer_front_panel_xdim-c3_drawer_interior_xdim)/2} 0
                                ${(-c3_drawer_interior_zdim+thickness)/2}"
                           xdim="${c3_drawer_interior_xdim}" ydim="${c3_drawer_interior_ydim}"
                           zdim="${c3_drawer_interior_zdim}"/>
  </xacro:macro>

  <xacro:macro name="pull_out" params="prefix name parent xyz">
    <xacro:box_link prefix="${prefix}" link_name="${name}_front_panel" mass="${pull_out_front_panel_mass}"
                    xdim="${pull_out_front_panel_xdim}" ydim="${pull_out_front_panel_ydim}"
                    zdim="${pull_out_front_panel_zdim}"
                    material="Oak"/>

    <joint name="${prefix}_${name}_front_panel_joint" type="prismatic">
      <parent link="${parent}"/>
      <child link="${prefix}_${name}_front_panel"/>
      <limit effort="10" lower="0" upper="${po_drawer_interior_xdim}" velocity="1"/>
      <dynamics damping="100" friction="0.1"/>
      <origin xyz="${xyz}"/>
      <axis xyz="1 0 0"/>
    </joint>

    <xacro:handle prefix="${prefix}" name="${name}" parent="${prefix}_${name}_front_panel"
                  xyz="${pull_out_front_panel_xdim/2} 0 ${pull_out_front_panel_zdim/2-0.05}"/>

    <xacro:drawer_interior prefix="${prefix}" name="${name}_drawer_1" parent="${prefix}_${name}_front_panel"
                           xyz="${(-pull_out_front_panel_xdim-po_drawer_interior_xdim)/2} 0
                                ${(pull_out_front_panel_zdim-po_drawer_interior_1_zdim)/2-0.15}"
                           xdim="${po_drawer_interior_xdim}" ydim="${po_drawer_interior_ydim}"
                           zdim="${po_drawer_interior_1_zdim}"/>

    <xacro:drawer_interior prefix="${prefix}" name="${name}_drawer_2" parent="${prefix}_${name}_front_panel"
                           xyz="${(-pull_out_front_panel_xdim-po_drawer_interior_xdim)/2} 0
                                ${(pull_out_front_panel_zdim-po_drawer_interior_1_zdim)/2-0.57}"
                           xdim="${po_drawer_interior_xdim}" ydim="${po_drawer_interior_ydim}"
                           zdim="${po_drawer_interior_2_zdim}"/>
  </xacro:macro>

  <!-- Assembles -->
  <xacro:macro name="bc_frame">
    <xacro:box_link prefix="bc_frame" link_name="base_link" mass="${bc_base_mass}" xdim="${bc_base_xdim}"
                    ydim="${bc_base_ydim}" zdim="${bc_base_zdim}" material="White"/>

    <xacro:box_link prefix="bc_frame" link_name="left_side_panel" mass="${bc_frame_side_panel_mass}"
                    xdim="${bc_frame_side_panel_xdim}" ydim="${bc_frame_side_panel_ydim}"
                    zdim="${bc_frame_side_panel_zdim}"
                    material="White"/>

    <joint name="bc_frame_left_side_panel_joint" type="fixed">
      <origin xyz="0 ${(bc_base_ydim-bc_frame_side_panel_ydim)/2} ${(bc_base_zdim+bc_frame_side_panel_zdim)/2}"
              rpy="0 0 0"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_left_side_panel"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="right_side_panel" mass="${bc_frame_side_panel_mass}"
                    xdim="${bc_frame_side_panel_xdim}" ydim="${bc_frame_side_panel_ydim}"
                    zdim="${bc_frame_side_panel_zdim}"
                    material="White"/>

    <joint name="bc_frame_right_side_panel_joint" type="fixed">
      <origin xyz="0 ${(-bc_base_ydim+bc_frame_side_panel_ydim)/2} ${(bc_base_zdim+bc_frame_side_panel_zdim)/2}"
              rpy="0 0 0"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_right_side_panel"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="back_panel" mass="${bc_frame_back_panel_mass}"
                    xdim="${bc_frame_back_panel_xdim}" ydim="${bc_frame_back_panel_ydim}"
                    zdim="${bc_frame_back_panel_zdim}"
                    material="White"/>

    <joint name="bc_frame_back_panel_joint" type="fixed">
      <origin xyz="${(-bc_base_xdim+bc_frame_back_panel_xdim)/2} 0 ${(bc_base_zdim+bc_frame_back_panel_zdim)/2}"
              rpy="0 0 0"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_back_panel"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="worktop" mass="${worktop_mass}"
                    xdim="${worktop_xdim}" ydim="${worktop_ydim}" zdim="${worktop_zdim}"
                    material="White"/>

    <joint name="bc_frame_worktop_joint" type="fixed">
      <origin xyz="0 0 ${(bc_base_zdim+worktop_zdim)/2+bc_frame_zdim}"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_worktop"/>
    </joint>

    <!-- Interior shelf -->
    <!-- Vertical -->
    <xacro:box_link prefix="bc_frame" link_name="c1_v_shelf" mass="${bc_v_shelf_mass}"
                    xdim="${bc_v_shelf_xdim}" ydim="${bc_v_shelf_ydim}" zdim="${bc_v_shelf_zdim}"
                    material="White"/>

    <joint name="bc_frame_c1_v_shelf_joint" type="fixed">
      <origin xyz="0 ${-bc_frame_ydim/2+bc_column_ydim} ${(bc_base_zdim+bc_frame_zdim)/2}"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_c1_v_shelf"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="c2_v_shelf" mass="${bc_v_shelf_mass}"
                    xdim="${bc_v_shelf_xdim}" ydim="${bc_v_shelf_ydim}" zdim="${bc_v_shelf_zdim}"
                    material="White"/>

    <joint name="bc_frame_c2_v_shelf_joint" type="fixed">
      <origin xyz="0 ${-bc_frame_ydim/2+bc_column_ydim*1.5} ${(bc_base_zdim+bc_frame_zdim)/2}"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_c2_v_shelf"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="c3_v_shelf" mass="${bc_v_shelf_mass}"
                    xdim="${bc_v_shelf_xdim}" ydim="${bc_v_shelf_ydim}" zdim="${bc_v_shelf_zdim}"
                    material="White"/>

    <joint name="bc_frame_c3_v_shelf_joint" type="fixed">
      <origin xyz="0 ${-bc_frame_ydim/2+bc_column_ydim*2.5} ${(bc_base_zdim+bc_frame_zdim)/2}"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_c3_v_shelf"/>
    </joint>

    <!-- Horizontal -->
    <xacro:box_link prefix="bc_frame" link_name="h1_shelf" mass="${bc_h_shelf_mass}"
                    xdim="${bc_h_shelf_xdim}" ydim="${bc_h_shelf_ydim}" zdim="${bc_h_shelf_zdim}"
                    material="White"/>

    <joint name="bc_frame_h1_shelf_joint" type="fixed">
      <origin xyz="0 ${-bc_frame_ydim/2+bc_column_ydim*3.5} ${(bc_base_zdim-bc_h_shelf_zdim)/2+bc_frame_zdim-0.24}"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_h1_shelf"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="h2_shelf" mass="${bc_h_shelf_mass}"
                    xdim="${bc_h_shelf_xdim}" ydim="${bc_h_shelf_ydim}" zdim="${bc_h_shelf_zdim}"
                    material="White"/>

    <joint name="bc_frame_h2_shelf_joint" type="fixed">
      <origin xyz="0 ${-bc_frame_ydim/2+bc_column_ydim*3.5} ${(bc_base_zdim-bc_h_shelf_zdim)/2+bc_frame_zdim-0.46}"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_h2_shelf"/>
    </joint>

  </xacro:macro>

  <xacro:macro name="base_cabinet" params="prefix connected_to:='' xyz:='0 0 0' rpy:='0 0 0'">
    <xacro:bc_frame/>

    <xacro:unless value="${not connected_to}">
      <joint name="${prefix}_${connected_to}_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="bc_frame_base_link"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
      </joint>
    </xacro:unless>

    <!-- The +x direction points from the back of the cabinet to the front -->
    <!-- Rightmost 1st column -->
    <xacro:door prefix="${prefix}" name="c1_door" parent="bc_frame_base_link"
                xyz="${(bc_frame_xdim+bc_door_xdim)/2} ${-bc_frame_ydim/2} ${(bc_base_zdim+bc_frame_zdim)/2}"
                mass="${bc_door_mass}" xdim="${bc_door_xdim}" ydim="${bc_door_ydim}" zdim="${bc_door_zdim}"
                hinge="right" handle_xyz="0.008 0.35 0.28" handle_rpy="${M_PI/2} 0 0"/>

    <xacro:drawer_interior prefix="${prefix}" name="c1_r1_drawer" parent="bc_frame_base_link"
                           xyz="${bc_frame_xdim/2} ${(-bc_frame_ydim+bc_column_ydim)/2}
                                ${bc_base_zdim+0.43+c1_r1_drawer_interior_zdim/2}"
                           xdim="${c1_r1_drawer_interior_xdim}" ydim="${c1_r1_drawer_interior_ydim}"
                           zdim="${c1_r1_drawer_interior_zdim}"
                           has_front_panel="true" has_side_panel="false" has_back_panel="false"/>

    <xacro:drawer_interior prefix="${prefix}" name="c1_r2_drawer" parent="bc_frame_base_link"
                           xyz="${bc_frame_xdim/2} ${(-bc_frame_ydim+bc_column_ydim)/2}
                                ${bc_base_zdim+0.12+c1_r2_drawer_interior_zdim/2}"
                           xdim="${c1_r2_drawer_interior_xdim}" ydim="${c1_r2_drawer_interior_ydim}"
                           zdim="${c1_r2_drawer_interior_zdim}" has_front_panel="true"/>

    <!-- Rightmost 2nd column -->
    <xacro:pull_out prefix="${prefix}" name="c2_pull_out" parent="bc_frame_base_link"
                    xyz="${(bc_frame_xdim+pull_out_front_panel_xdim)/2}
                         ${-bc_frame_ydim/2+bc_column_ydim*1.25}
                         ${(bc_base_zdim+bc_frame_zdim)/2}"/>

    <!-- Rightmost 3rd column -->
    <xacro:drawer prefix="${prefix}" name="c3_r1_drawer" parent="bc_frame_base_link"
                  xyz="${(bc_frame_xdim+drawer_front_panel_xdim)/2}
                       ${-bc_frame_ydim/2+bc_column_ydim*2}
                       ${(bc_base_zdim-bc_row_zdim)/2+bc_frame_zdim}"/>

    <xacro:drawer prefix="${prefix}" name="c3_r2_drawer" parent="bc_frame_base_link"
                  xyz="${(bc_frame_xdim+drawer_front_panel_xdim)/2}
                       ${-bc_frame_ydim/2+bc_column_ydim*2}
                       ${(bc_base_zdim-bc_row_zdim*3)/2+bc_frame_zdim}"/>

    <xacro:drawer prefix="${prefix}" name="c3_r3_drawer" parent="bc_frame_base_link"
                  xyz="${(bc_frame_xdim+drawer_front_panel_xdim)/2}
                       ${-bc_frame_ydim/2+bc_column_ydim*2}
                       ${(bc_base_zdim-bc_row_zdim*5)/2+bc_frame_zdim}"/>

    <xacro:drawer prefix="${prefix}" name="c3_r4_drawer" parent="bc_frame_base_link"
                  xyz="${(bc_frame_xdim+drawer_front_panel_xdim)/2}
                       ${-bc_frame_ydim/2+bc_column_ydim*2}
                       ${(bc_base_zdim-bc_row_zdim*7)/2+bc_frame_zdim}"/>

    <!-- Rightmost 4th column -->
    <xacro:door prefix="${prefix}" name="c4_door" parent="bc_frame_base_link"
                xyz="${(bc_frame_xdim+bc_door_xdim)/2}
                     ${-bc_frame_ydim/2+bc_column_ydim*2.5}
                     ${(bc_base_zdim+bc_frame_zdim)/2}"
                mass="${bc_door_mass}" xdim="${bc_door_xdim}" ydim="${bc_door_ydim}" zdim="${bc_door_zdim}"
                hinge="right" handle_xyz="0.008 0.35 0.28" handle_rpy="${M_PI/2} 0 0"/>

    <!-- Rightmost 5th column -->
    <xacro:door prefix="${prefix}" name="c5_door" parent="bc_frame_base_link"
                xyz="${(bc_frame_xdim+bc_door_xdim)/2}
                     ${-bc_frame_ydim/2+bc_column_ydim*4.5}
                     ${(bc_base_zdim+bc_frame_zdim)/2}"
                mass="${bc_door_mass}" xdim="${bc_door_xdim}" ydim="${bc_door_ydim}" zdim="${bc_door_zdim}"
                hinge="left" handle_xyz="0.008 -0.35 0.28" handle_rpy="${M_PI/2} 0 0"/>
  </xacro:macro>

</robot>
