<?xml version="1.0"?>
<robot name="base_cabinet" xmlns:xacro="http://wiki.ros.org/xacro">

  <!-- Using meter, kg -->
  <xacro:property name="base_xdim" value="0.6"/>
  <xacro:property name="base_ydim" value="1.8"/>
  <xacro:property name="base_zdim" value="0.08"/>
  <xacro:property name="base_mass" value="20"/>

  <!-- Frame refers to the main part of the cabinet -->
  <xacro:property name="bc_frame_xdim" value="0.6"/>
  <xacro:property name="bc_frame_ydim" value="1.8"/>
  <xacro:property name="bc_frame_zdim" value="0.8"/>

  <xacro:property name="column_ydim" value="0.4"/>
  <xacro:property name="row_zdim" value="${bc_frame_zdim/4}"/>

  <xacro:property name="thickness" value="0.016"/>
  <xacro:property name="tolerance" value="0.004"/>

  <xacro:property name="bc_frame_back_panel_xdim" value="${thickness}"/>
  <xacro:property name="bc_frame_back_panel_ydim" value="${bc_frame_ydim}"/>
  <xacro:property name="bc_frame_back_panel_zdim" value="${bc_frame_zdim}"/>
  <xacro:property name="bc_frame_back_panel_mass" value="20"/>

  <xacro:property name="bc_frame_side_panel_xdim" value="${bc_frame_xdim}"/>
  <xacro:property name="bc_frame_side_panel_ydim" value="${thickness}"/>
  <xacro:property name="bc_frame_side_panel_zdim" value="${bc_frame_zdim}"/>
  <xacro:property name="bc_frame_side_panel_mass" value="5"/>

  <!-- https://www.ikea.com.hk/zh/products/kitchen-worktops/kitchen-worktops/lilltrask-art-40280659-->
  <xacro:property name="worktop_xdim" value="0.635"/>
  <xacro:property name="worktop_ydim" value="1.86"/>
  <xacro:property name="worktop_zdim" value="0.028"/>
  <xacro:property name="worktop_mass" value="20.65"/>

  <!-- https://www.ikea.com.hk/en/products/kitchen-fronts/kitchen-fronts-cover-panels-and-plinth/enhet-art-90481556 -->
  <xacro:property name="door_xdim" value="${thickness}"/>
  <xacro:property name="door_ydim" value="${column_ydim-tolerance}"/>
  <xacro:property name="door_zdim" value="${bc_frame_zdim-tolerance}"/>
  <xacro:property name="door_mass" value="3.31"/>

  <!-- https://www.ikea.com.hk/en/products/kitchen-fronts/kitchen-fronts-cover-panels-and-plinth/enhet-art-30481559 -->
  <xacro:property name="drawer_front_panel_xdim" value="${thickness}"/>
  <xacro:property name="drawer_front_panel_ydim" value="${column_ydim-tolerance}"/>
  <xacro:property name="drawer_front_panel_zdim" value="${row_zdim-tolerance}"/>
  <xacro:property name="drawer_front_panel_mass" value="0.75"/>

  <!-- Drawer interior, bc_frame size: X60cm Y40cm Z20cm -->
  <!-- https://www.ikea.com.hk/en/products/kitchen-fixed-interiors/kitchen-fixed-interiors/maximera-art-70271111-->
  <xacro:property name="drawer_interior_xdim" value="0.542"/>
  <xacro:property name="drawer_interior_ydim" value="0.364"/>
  <xacro:property name="drawer_interior_zdim" value="0.144"/>

  <xacro:property name="drawer_side_panel_xdim" value="${drawer_interior_xdim}"/>
  <xacro:property name="drawer_side_panel_ydim" value="${thickness}"/>
  <xacro:property name="drawer_side_panel_zdim" value="${drawer_interior_zdim}"/>
  <xacro:property name="drawer_side_panel_mass" value="2"/>

  <xacro:property name="drawer_bottom_panel_xdim" value="${drawer_interior_xdim}"/>
  <xacro:property name="drawer_bottom_panel_ydim" value="${drawer_interior_ydim}"/>
  <xacro:property name="drawer_bottom_panel_zdim" value="${thickness}"/>
  <xacro:property name="drawer_bottom_panel_mass" value="3"/>

  <xacro:property name="drawer_back_panel_xdim" value="${thickness}"/>
  <xacro:property name="drawer_back_panel_ydim" value="${drawer_interior_ydim}"/>
  <xacro:property name="drawer_back_panel_zdim" value="${drawer_interior_zdim}"/>
  <xacro:property name="drawer_back_panel_mass" value="2"/>

  <!-- https://www.ikea.com.hk/en/products/kitchen-fronts/kitchen-fronts-cover-panels-and-plinth/askersund-art-50331776-->
  <xacro:property name="pull_out_front_panel_xdim" value="${thickness}"/>
  <xacro:property name="pull_out_front_panel_ydim" value="0.197"/>
  <xacro:property name="pull_out_front_panel_zdim" value="0.797"/>
  <xacro:property name="pull_out_front_panel_mass" value="1.66"/>

  <!-- https://www.ikea.com.hk/en/products/kitchen-fixed-interiors/kitchen-fixed-interiors/maximera-art-80297276-->

  <xacro:macro name="drawer" params="prefix name parent xyz">
    <xacro:box_link prefix="${prefix}" link_name="${name}_front_panel" mass="${drawer_front_panel_mass}"
                    xdim="${drawer_front_panel_xdim}" ydim="${drawer_front_panel_ydim}"
                    zdim="${drawer_front_panel_zdim}"
                    material="Oak"/>

    <joint name="${prefix}_${name}_front_panel_joint" type="prismatic">
      <parent link="${parent}"/>
      <child link="${prefix}_${name}_front_panel"/>
      <limit effort="10" lower="0" upper="${drawer_bottom_panel_xdim}" velocity="1"/>
      <dynamics damping="100" friction="0.1"/>
      <origin xyz="${xyz}"/>
      <axis xyz="1 0 0"/>
    </joint>

    <xacro:box_link prefix="${prefix}" link_name="${name}_bottom_panel" mass="${drawer_bottom_panel_mass}"
                    xdim="${drawer_bottom_panel_xdim}" ydim="${drawer_bottom_panel_ydim}"
                    zdim="${drawer_bottom_panel_zdim}"
                    material="White"/>

    <joint name="${prefix}_${name}_bottom_panel_joint" type="fixed">
      <parent link="${prefix}_${name}_front_panel"/>
      <child link="${prefix}_${name}_bottom_panel"/>
      <origin xyz="${(-drawer_front_panel_xdim-drawer_bottom_panel_xdim)/2}
                    0 ${-drawer_side_panel_zdim/2+drawer_bottom_panel_zdim}"
      />
    </joint>

    <xacro:box_link prefix="${prefix}" link_name="${name}_left_side_panel" mass="${drawer_side_panel_mass}"
                    xdim="${drawer_side_panel_xdim}" ydim="${drawer_side_panel_ydim}" zdim="${drawer_side_panel_zdim}"
                    material="Glass"/>

    <joint name="${prefix}_${name}_left_side_panel_joint" type="fixed">
      <parent link="${prefix}_${name}_front_panel"/>
      <child link="${prefix}_${name}_left_side_panel"/>
      <origin xyz="${(-drawer_front_panel_xdim-drawer_side_panel_xdim)/2}
                    ${(drawer_front_panel_ydim-drawer_side_panel_ydim)/2} 0"
      />
    </joint>

    <xacro:box_link prefix="${prefix}" link_name="${name}_right_side_panel" mass="${drawer_side_panel_mass}"
                    xdim="${drawer_side_panel_xdim}" ydim="${drawer_side_panel_ydim}" zdim="${drawer_side_panel_zdim}"
                    material="Glass"/>

    <joint name="${prefix}_${name}_right_side_panel_joint" type="fixed">
      <parent link="${prefix}_${name}_front_panel"/>
      <child link="${prefix}_${name}_right_side_panel"/>
      <origin xyz="${(-drawer_front_panel_xdim-drawer_side_panel_xdim)/2}
                    ${(-drawer_front_panel_ydim+drawer_side_panel_ydim)/2} 0"
      />
    </joint>

    <xacro:box_link prefix="${prefix}" link_name="${name}_back_panel" mass="${drawer_back_panel_mass}"
                    xdim="${drawer_back_panel_xdim}" ydim="${drawer_back_panel_ydim}" zdim="${drawer_back_panel_zdim}"
                    material="White"/>

    <joint name="${prefix}_${name}_back_panel_joint" type="fixed">
      <parent link="${prefix}_${name}_front_panel"/>
      <child link="${prefix}_${name}_back_panel"/>
      <origin xyz="${(-drawer_front_panel_xdim-drawer_back_panel_xdim)/2-drawer_side_panel_xdim}
                    0 0"
      />
    </joint>
  </xacro:macro>

  <xacro:macro name="pull_out" params="prefix name parent xyz">
    <xacro:box_link prefix="${prefix}" link_name="${name}_front_panel" mass="${pull_out_front_panel_mass}"
                    xdim="${pull_out_front_panel_xdim}" ydim="${pull_out_front_panel_ydim}"
                    zdim="${pull_out_front_panel_zdim}"
                    material="Oak"/>

    <joint name="${prefix}_${name}_front_panel_joint" type="prismatic">
      <parent link="${parent}"/>
      <child link="${prefix}_${name}_front_panel"/>
      <limit effort="10" lower="0" upper="${drawer_bottom_panel_xdim}" velocity="1"/>
      <dynamics damping="100" friction="0.1"/>
      <origin xyz="${xyz}"/>
      <axis xyz="1 0 0"/>
    </joint>

    <!--    <xacro:box_link prefix="${prefix}" link_name="${name}_bottom_panel" mass="${drawer_bottom_panel_mass}"-->
    <!--                    xdim="${drawer_bottom_panel_xdim}" ydim="${drawer_bottom_panel_ydim}"-->
    <!--                    zdim="${drawer_bottom_panel_zdim}"-->
    <!--                    material="White"/>-->

    <!--    <joint name="${prefix}_${name}_bottom_panel_joint" type="fixed">-->
    <!--      <parent link="${prefix}_${name}_front_panel"/>-->
    <!--      <child link="${prefix}_${name}_bottom_panel"/>-->
    <!--      <origin xyz="${(-drawer_front_panel_xdim-drawer_bottom_panel_xdim)/2}-->
    <!--                    0 ${(-drawer_front_panel_zdim+drawer_bottom_panel_zdim)/2}"-->
    <!--      />-->
    <!--    </joint>-->

    <!--    <xacro:box_link prefix="${prefix}" link_name="${name}_left_side_panel" mass="${drawer_side_panel_mass}"-->
    <!--                    xdim="${drawer_side_panel_xdim}" ydim="${drawer_side_panel_ydim}" zdim="${drawer_side_panel_zdim}"-->
    <!--                    material="White"/>-->

    <!--    <joint name="${prefix}_${name}_left_side_panel_joint" type="fixed">-->
    <!--      <parent link="${prefix}_${name}_front_panel"/>-->
    <!--      <child link="${prefix}_${name}_left_side_panel"/>-->
    <!--      <origin xyz="${(-drawer_front_panel_xdim-drawer_side_panel_xdim)/2}-->
    <!--                    ${(drawer_front_panel_ydim-drawer_side_panel_ydim)/2} 0"-->
    <!--      />-->
    <!--    </joint>-->

    <!--    <xacro:box_link prefix="${prefix}" link_name="${name}_right_side_panel" mass="${drawer_side_panel_mass}"-->
    <!--                    xdim="${drawer_side_panel_xdim}" ydim="${drawer_side_panel_ydim}" zdim="${drawer_side_panel_zdim}"-->
    <!--                    material="White"/>-->

    <!--    <joint name="${prefix}_${name}_right_side_panel_joint" type="fixed">-->
    <!--      <parent link="${prefix}_${name}_front_panel"/>-->
    <!--      <child link="${prefix}_${name}_right_side_panel"/>-->
    <!--      <origin xyz="${(-drawer_front_panel_xdim-drawer_side_panel_xdim)/2}-->
    <!--                    ${(-drawer_front_panel_ydim+drawer_side_panel_ydim)/2} 0"-->
    <!--      />-->
    <!--    </joint>-->
  </xacro:macro>

  <!-- Assembles -->
  <xacro:macro name="bc_frame">
    <xacro:box_link prefix="bc_frame" link_name="base_link" mass="${base_mass}" xdim="${base_xdim}" ydim="${base_ydim}"
                    zdim="${base_zdim}" material="White"/>

    <xacro:box_link prefix="bc_frame" link_name="left_side_panel" mass="${bc_frame_side_panel_mass}"
                    xdim="${bc_frame_side_panel_xdim}" ydim="${bc_frame_side_panel_ydim}"
                    zdim="${bc_frame_side_panel_zdim}"
                    material="White"/>

    <joint name="bc_frame_left_side_panel_joint" type="fixed">
      <origin xyz="0 ${(base_ydim-bc_frame_side_panel_ydim)/2} ${(base_zdim+bc_frame_side_panel_zdim)/2}" rpy="0 0 0"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_left_side_panel"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="right_side_panel" mass="${bc_frame_side_panel_mass}"
                    xdim="${bc_frame_side_panel_xdim}" ydim="${bc_frame_side_panel_ydim}"
                    zdim="${bc_frame_side_panel_zdim}"
                    material="White"/>

    <joint name="bc_frame_right_side_panel_joint" type="fixed">
      <origin xyz="0 ${(-base_ydim+bc_frame_side_panel_ydim)/2} ${(base_zdim+bc_frame_side_panel_zdim)/2}" rpy="0 0 0"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_right_side_panel"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="back_panel" mass="${bc_frame_back_panel_mass}"
                    xdim="${bc_frame_back_panel_xdim}" ydim="${bc_frame_back_panel_ydim}"
                    zdim="${bc_frame_back_panel_zdim}"
                    material="White"/>

    <joint name="bc_frame_back_panel_joint" type="fixed">
      <origin xyz="${(-base_xdim+bc_frame_back_panel_xdim)/2} 0 ${(base_zdim+bc_frame_back_panel_zdim)/2}" rpy="0 0 0"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_back_panel"/>
    </joint>

    <xacro:box_link prefix="bc_frame" link_name="worktop" mass="${worktop_mass}"
                    xdim="${worktop_xdim}" ydim="${worktop_ydim}" zdim="${worktop_zdim}"
                    material="White"/>

    <joint name="bc_frame_worktop_joint" type="fixed">
      <origin xyz="0 0 ${(base_zdim+worktop_zdim)/2+bc_frame_back_panel_zdim}" rpy="0 0 0"/>
      <parent link="bc_frame_base_link"/>
      <child link="bc_frame_worktop"/>
    </joint>
  </xacro:macro>

  <xacro:macro name="base_cabinet" params="prefix connected_to:='' xyz:='0 0 0' rpy:='0 0 0'">
    <xacro:bc_frame/>

    <xacro:unless value="${not connected_to}">
      <joint name="${prefix}_${connected_to}_joint" type="fixed">
        <parent link="${connected_to}"/>
        <child link="bc_frame_base_link"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
      </joint>
    </xacro:unless>

    <!-- The +x direction points from the back of the cabinet to the front -->
    <!-- Rightmost 1st column -->
    <xacro:door prefix="${prefix}" name="c1_door" parent="bc_frame_base_link"
                xyz="${base_xdim/2} ${-base_ydim/2+bc_frame_side_panel_ydim} ${(base_zdim+bc_frame_side_panel_zdim)/2}"
                mass="${door_mass}" xdim="${door_xdim}" ydim="${door_ydim}" zdim="${door_zdim}"
                hinge="right"/>

    <!-- Rightmost 2nd column -->
    <xacro:pull_out prefix="${prefix}" name="c2_pull_out" parent="bc_frame_base_link"
                    xyz="${(base_xdim+thickness)/2} ${base_ydim/2-bc_frame_side_panel_ydim-column_ydim*3.25}
                       ${(base_zdim+bc_frame_zdim)/2}"/>

    <!-- Rightmost 3rd column -->
    <xacro:drawer prefix="${prefix}" name="c3_r1_drawer" parent="bc_frame_base_link"
                  xyz="${(base_xdim+drawer_front_panel_xdim)/2} ${base_ydim/2-bc_frame_side_panel_ydim-column_ydim*2.5}
                     ${(base_zdim-row_zdim)/2+bc_frame_zdim}"/>

    <xacro:drawer prefix="${prefix}" name="c3_r2_drawer" parent="bc_frame_base_link"
                  xyz="${(base_xdim+drawer_front_panel_xdim)/2} ${base_ydim/2-bc_frame_side_panel_ydim-column_ydim*2.5}
                     ${(base_zdim-row_zdim*3)/2+bc_frame_zdim}"/>

    <xacro:drawer prefix="${prefix}" name="c3_r3_drawer" parent="bc_frame_base_link"
                  xyz="${(base_xdim+drawer_front_panel_xdim)/2} ${base_ydim/2-bc_frame_side_panel_ydim-column_ydim*2.5}
                     ${(base_zdim-row_zdim*5)/2+bc_frame_zdim}"/>

    <xacro:drawer prefix="${prefix}" name="c3_r4_drawer" parent="bc_frame_base_link"
                  xyz="${(base_xdim+drawer_front_panel_xdim)/2} ${base_ydim/2-bc_frame_side_panel_ydim-column_ydim*2.5}
                     ${(base_zdim-row_zdim*7)/2+bc_frame_zdim}"/>

    <!-- Rightmost 4th column -->
    <xacro:door prefix="${prefix}" name="c4_door" parent="bc_frame_base_link"
                xyz="${base_xdim/2} ${base_ydim/2-bc_frame_side_panel_ydim-column_ydim*2} ${(base_zdim+bc_frame_side_panel_zdim)/2}"
                mass="${door_mass}" xdim="${door_xdim}" ydim="${door_ydim}" zdim="${door_zdim}"
                hinge="right"/>

    <!-- Rightmost 5th column -->
    <xacro:door prefix="${prefix}" name="c5_door" parent="bc_frame_base_link"
                xyz="${base_xdim/2} ${base_ydim/2-bc_frame_side_panel_ydim} ${(base_zdim+bc_frame_side_panel_zdim)/2}"
                mass="${door_mass}" xdim="${door_xdim}" ydim="${door_ydim}" zdim="${door_zdim}"
                hinge="left"/>
  </xacro:macro>

</robot>
