<?xml version="1.0"?>
<robot name="components" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:property name="M_PI" value="3.1415926535897931"/>

  <!-- https://www.ikea.com.hk/en/products/knobs-and-handles/knobs-and-handles/bagganas-art-70338423 -->
  <xacro:property name="handle_mass" value="0.09"/>

  <xacro:macro name="box_inertia" params="mass xdim ydim zdim">
    <inertia ixx="${mass * (ydim * ydim + zdim * zdim) / 12}" ixy="0" ixz="0"
             iyy="${mass * (xdim * xdim + zdim * zdim) / 12}" iyz="0"
             izz="${mass * (ydim * ydim + xdim * xdim) / 12}"/>
  </xacro:macro>

  <xacro:macro name="box_link" params="prefix link_name mass xdim ydim zdim material hinge='none'">
    <link name="${prefix}_${link_name}">
      <visual>
        <xacro:if value="${hinge == 'right'}">
          <origin xyz="0 ${ydim/2} 0"/>
        </xacro:if>
        <xacro:if value="${hinge == 'left'}">
          <origin xyz="0 ${-ydim/2} 0"/>
        </xacro:if>
        <xacro:if value="${hinge == 'none'}">
          <origin xyz="0 0 0"/>
        </xacro:if>
        <geometry>
          <box size="${xdim} ${ydim} ${zdim}"/>
        </geometry>
        <material name="${material}"/>
      </visual>

      <collision>
        <xacro:if value="${hinge == 'right'}">
          <origin xyz="0 ${ydim/2} 0"/>
        </xacro:if>
        <xacro:if value="${hinge == 'left'}">
          <origin xyz="0 ${-ydim/2} 0"/>
        </xacro:if>
        <xacro:if value="${hinge == 'none'}">
          <origin xyz="0 0 0"/>
        </xacro:if>
        <geometry>
          <box size="${xdim} ${ydim} ${zdim}"/>
        </geometry>
      </collision>

      <inertial>
        <xacro:if value="${hinge == 'right'}">
          <origin xyz="0 ${ydim/2} 0"/>
        </xacro:if>
        <xacro:if value="${hinge == 'left'}">
          <origin xyz="0 ${-ydim/2} 0"/>
        </xacro:if>
        <xacro:if value="${hinge == 'none'}">
          <origin xyz="0 0 0"/>
        </xacro:if>
        <mass value="${mass}"/>
        <xacro:box_inertia mass="${mass}" xdim="${xdim}" ydim="${ydim}" zdim="${zdim}"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="handle" params="prefix name parent xyz rpy:='0 0 0'">
    <link name="${prefix}_${name}_handle_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://clover_lab/meshes/handle.stl"/>
        </geometry>
        <material name="Black"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://clover_lab/meshes/handle.stl"/>
        </geometry>
      </collision>

      <inertial>
        <mass value="${handle_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="${211.711 * 1e-6}" ixy="0" ixz="0"
                 iyy="${63.764 * 1e-6}" iyz="0"
                 izz="${274.426 * 1e-6}"/>
      </inertial>
    </link>

    <joint name="${prefix}_${name}_handle_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_${name}_handle_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

  </xacro:macro>

  <xacro:macro name="door" params="prefix name parent xyz mass xdim ydim zdim hinge handle_xyz handle_rpy">
    <xacro:box_link prefix="${prefix}" link_name="${name}" mass="${mass}"
                    xdim="${xdim}" ydim="${ydim}" zdim="${zdim}"
                    material="Oak" hinge="${hinge}"/>

    <joint name="${prefix}_${name}_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${prefix}_${name}"/>
      <limit effort="10" lower="0" upper="${M_PI / 2}" velocity="1"/>
      <dynamics damping="100" friction="0.1"/>
      <origin xyz="${xyz}"/>
      <xacro:if value="${hinge == 'right'}">
        <axis xyz="0 0 -1"/>
      </xacro:if>
      <xacro:unless value="${hinge == 'right'}">
        <axis xyz="0 0 1"/>
      </xacro:unless>
    </joint>

    <xacro:handle prefix="${prefix}" name="${name}" parent="${prefix}_${name}" xyz="${handle_xyz}" rpy="${handle_rpy}"/>
  </xacro:macro>

  <xacro:macro name="drawer_interior"
               params="prefix name parent xyz xdim ydim zdim
                       has_front_panel:=false has_side_panel:=true has_back_panel:=true">

    <xacro:if value="${has_front_panel}">

      <xacro:box_link prefix="${prefix}" link_name="${name}_front_panel" mass="5"
                      xdim="${thickness}" ydim="${ydim}" zdim="${zdim}" material="White"/>

      <joint name="${prefix}_${name}_front_panel_joint" type="prismatic">
        <parent link="${parent}"/>
        <child link="${prefix}_${name}_front_panel"/>
        <origin xyz="${xyz}"/>
        <limit effort="10" velocity="1" lower="0" upper="${xdim}"/>
        <axis xyz="1 0 0"/>
      </joint>

      <xacro:box_link prefix="${prefix}" link_name="${name}_bottom_panel" mass="5"
                      xdim="${xdim}" ydim="${ydim}" zdim="${thickness}" material="White"/>

      <joint name="${prefix}_${name}_bottom_panel_joint" type="fixed">
        <parent link="${prefix}_${name}_front_panel"/>
        <child link="${prefix}_${name}_bottom_panel"/>
        <origin xyz="${(-xdim+thickness)/2} 0 ${(-zdim+thickness)/2}"/>
      </joint>

    </xacro:if>

    <xacro:unless value="${has_front_panel}">

      <xacro:box_link prefix="${prefix}" link_name="${name}_bottom_panel" mass="5"
                      xdim="${xdim}" ydim="${ydim}" zdim="${thickness}"
                      material="White"/>

      <joint name="${prefix}_${name}_bottom_panel_joint" type="fixed">
        <parent link="${parent}"/>
        <child link="${prefix}_${name}_bottom_panel"/>
        <origin xyz="${xyz}"/>
      </joint>

    </xacro:unless>

    <xacro:if value="${has_side_panel}">
      <xacro:box_link prefix="${prefix}" link_name="${name}_left_side_panel" mass="1"
                      xdim="${xdim}" ydim="${thickness}" zdim="${zdim}"
                      material="Glass"/>

      <joint name="${prefix}_${name}_left_side_panel_joint" type="fixed">
        <parent link="${prefix}_${name}_bottom_panel"/>
        <child link="${prefix}_${name}_left_side_panel"/>
        <origin xyz="0 ${(ydim-thickness)/2} ${(zdim-thickness)/2}"
        />
      </joint>

      <xacro:box_link prefix="${prefix}" link_name="${name}_right_side_panel" mass="1"
                      xdim="${xdim}" ydim="${thickness}" zdim="${zdim}"
                      material="Glass"/>

      <joint name="${prefix}_${name}_right_side_panel_joint" type="fixed">
        <parent link="${prefix}_${name}_bottom_panel"/>
        <child link="${prefix}_${name}_right_side_panel"/>
        <origin xyz="0 ${(-ydim+thickness)/2} ${(zdim-thickness)/2}"
        />
      </joint>
    </xacro:if>

    <xacro:if value="${has_back_panel}">
      <xacro:box_link prefix="${prefix}" link_name="${name}_back_panel" mass="2"
                      xdim="${thickness}" ydim="${ydim}" zdim="${zdim}"
                      material="White"/>

      <joint name="${prefix}_${name}_back_panel_joint" type="fixed">
        <parent link="${prefix}_${name}_bottom_panel"/>
        <child link="${prefix}_${name}_back_panel"/>
        <origin xyz="${(-xdim+thickness)/2} 0 ${(zdim-thickness)/2}"
        />
      </joint>
    </xacro:if>

  </xacro:macro>

</robot>
